# Generated by Django 4.2.7 on 2024-05-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
