# Generated by Django 4.2.7 on 2024-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0004_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunjabiItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
