# Generated by Django 4.2.9 on 2024-05-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='departmnent',
            new_name='department',
        ),
    ]
